#+TITLE: A Pomodoro Timer That Locks You Out

There are tons of pomodoro timers out there, some simple, some complex, but in
my experience they all have the same problem.

The alarm goes off and I think "huh" and keep working.

This is a bash script that uses [[https://github.com/Raymo111/i3lock-color][i3lock-color]] or [[https://github.com/mortie/swaylock-effects][swaylock]] to completely lock your
screen when the timer goes off and then keeps you out for the duration of the
break, forcing you to step away from your work for a moment.

This is a super simple tool. It just schedules a time for the screen to lock,
and then pops the lock screen back up immediately if you try to get in during
the break. There is no timer indicating how much time is left. There are no
provisions for not locking the screen in certain cases (like if you are watching
a fullscreen video). And I have no idea how it performs with multiple monitors.

* Install
You will need the following dependencies installed

- systemd
- [[https://imagemagick.org/script/convert.php][convert]], part of the imagemagick suite

If using i3:
- [[https://github.com/Raymo111/i3lock-color][i3lock-color]] (version 2.13.c.3, anything older you will need to change the
  options flags to their pre-standardized versions)
- [[https://github.com/naelstrof/maim][maim]] screenshot tool (although this could easily be swapped out)

If using Sway:
- [[https://github.com/mortie/swaylock-effects][swaylock-effects]]
- [[https://github.com/emersion/grim][grim]] screenshot tool

Then clone this repo and run the ~install.sh~ script, which symlinks the
necessary files to appropriate locations. (Using symlinks makes it easier to
change behavior without chasing all over the file system.)

* Usage
The timer will start when you login after boot. The default time is 35 minutes
with a 10 minute break.

To start the timer manually, run

#+begin_src shell
systemctl --user start screenlock.timer
#+end_src

This will start the timer with a remaining time RELATIVE TO BOOT TIME (I think),
not relative to the time you invoke the command.

To cancel a timer, run

#+begin_src shell
systemctl --user stop screenlock.timer
#+end_src
